# Generated by Django 3.1.3 on 2024-02-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
