# Generated by Django 3.1.3 on 2024-02-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20240217_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='hpNumber',
            new_name='mobileNumber',
        ),
    ]
