# Generated by Django 3.1.3 on 2024-03-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20240217_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
